name: dependency_scanner
description: Dart Dependency Scanner for local projects in a workspace. Allows automated upgrades, pug get and more.
version: 1.0.5
homepage: https://github.com/gmpassos/dependency_scanner

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.7.0
  pubspec: ^0.1.4
  pub_semver: ^1.4.4
  pub_client: ^3.0.3
  swiss_knife: ^2.4.1
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.14.5

executables:
  depscan:

